version: 2
jobs:
  test2.7:
    working_directory: /
    docker:
      - image: circleci/python:2.7-stretch-browsers
    steps:
      - checkout
      - run:
          command: python ./test_send_signifai.py
  test3.6:
    working_directory: /
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
    steps:
      - checkout
      - run:
          command: python ./test_send_signifai.py
workflows:
  version: 2
  test:
    jobs:
      - test2.7
      - test3.6