version: 2
jobs:
  test2.7:
    working_directory: ~/repo
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          command: |
            # mock was backported, we have to install it first
            pip install mock
            # tests assume Pacific timezone (this is deliberate
            # because Zabbix provides times in local time zone)
            sudo ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
            python ./test_send_signifai.py
  test3.6:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            # tests assume Pacific timezone (this is deliberate
            # because Zabbix provides times in local time zone)
            sudo ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
            python ./test_send_signifai.py
workflows:
  version: 2
  test:
    jobs:
      - test2.7
      - test3.6